export const monthly = {
  id: 1,
  slug: "free",
  tag: null,
  title: "Free trial",
  price: "0.00",
  period: "month",
  tier: "monthly",
  subtitle: "Free trail for first 3 months",
  features: [
    "Add 1 child",
    "Tracking Milstone of developing",
    "Daily tips and articles ",
    "Moitoring grwoth and weight",
    "Share your lovely moments by uploading your picture",
    "Monlthy updating report",
    "Uploding medical report",
    "Reminders",
    "Support",
  ],
};
export const yearly = {
  id: 1,
  slug: "free",
  tag: null,
  title: "Free trial",
  price: "0.00",
  old_price: null,
  period: "3 month",
  tier: "yearly",
  subtitle: "Free trail for first 3 months",
  features: [
    "Add 1 child",
    "Tracking Milstone of developing",
    "Daily tips and articles",
    "Monitoring grwoth and weight",
    "Share your lovely moments by uploading your picture",
    "Monlthy updating report",
    "Uploding medical report",
    "Reminders",
    "Support",
  ],
};
